databases:
  - name: redash
    databaseName: redash
    user: redash
    region: singapore

services:
  # Do not forget to run `render-redash create_db` in Render Shell after creating this service.
  # If you have upgraded from a previous version, run `render-redash manage db upgrade` instead.
  - type: web
    name: redash-server
    plan: standard
    region: singapore
    env: docker
    dockerCommand: render-redash server
    healthCheckPath: /ping
    envVars:
      - key: PORT
        value: 5000
      - key: REDASH_DATABASE_URL
        fromDatabase:
          name: redash
          property: connectionString
      - key: REDASH_REDIS_URL
        fromService:
          type: redis
          name: redash-redis
          property: connectionString
      - fromGroup: redash-shared
      - fromGroup: redash-mail

  - type: worker
    name: redash-scheduler
    plan: starter
    region: singapore
    env: docker
    dockerCommand: render-redash scheduler
    envVars:
      - key: REDASH_DATABASE_URL
        fromDatabase:
          name: redash
          property: connectionString
      - key: REDASH_REDIS_URL
        fromService:
          type: redis
          name: redash-redis
          property: connectionString
      - fromGroup: redash-shared
      - fromGroup: redash-mail

  - type: worker
    name: redash-worker
    plan: starter
    region: singapore
    env: docker
    dockerCommand: render-redash worker
    envVars:
      - key: REDASH_DATABASE_URL
        fromDatabase:
          name: redash
          property: connectionString
      - key: REDASH_REDIS_URL
        fromService:
          type: redis
          name: redash-redis
          property: connectionString
      - fromGroup: redash-shared
      - fromGroup: redash-mail
      - key: QUEUES
        value: "queries,scheduled_queries,schemas"
      - key: WORKERS_COUNT
        value: 2

  - type: redis
    name: redash-redis
    plan: free
    region: singapore
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

envVarGroups:
  - name: redash-shared
    envVars:
      - key: REDASH_COOKIE_SECRET
        value: "UcRlCHoFyGLMQW4jwp2IWDHLosOcxg8D"
      - key: REDASH_SECRET_KEY
        value: "lRGECAlm1vPLAMRkAhZrx2m03OAdh5HF"
      - key: REDASH_LOG_LEVEL
        value: "INFO"

  # Uncomment and fill following fields if you wish to set up mailing in Redash.
  # It’s recommended to use some mail service, like Amazon SES or Mailgun
  # to send emails to ensure deliverability.
  - name: redash-mail
    envVars:
#      - key: REDASH_MAIL_SERVER
#        value: (SMTP server address)
#      - key: REDASH_MAIL_PORT
#        value: 25
#      - key: REDASH_MAIL_USE_TLS
#        value: false
#      - key: REDASH_MAIL_USE_SSL
#        value: false
#      - key: REDASH_MAIL_USERNAME
#        value: None
#      - key: REDASH_MAIL_PASSWORD
#        value: None
#      - key: REDASH_MAIL_DEFAULT_SENDER
#        value: (Email address to send from)
